In [2]:
import numpy as np

# Q1: Creating a 1D NumPy array with 5 elements and performing operations
a = np.array([1, 2, 3, 4, 5])
print("Original Array:", a)
print("Addition of 2:", a + 2)
print("Multiplication by 3:", a * 3)
print("Division by 2:", a / 2)

Original Array: [1 2 3 4 5]
Addition of 2: [3 4 5 6 7]
Multiplication by 3: [ 3  6  9 12 15]
Division by 2: [0.5 1.  1.5 2.  2.5]


In [4]:
# Q2a: Reverse the array
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed Array:", arr[::-1])

Reversed Array: [5 4 6 3 2 1]


In [6]:
# Q2b: Finding the most frequent value and its indices in arrays
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
most_freq_x = np.bincount(x).argmax()
most_freq_y = np.bincount(y).argmax()
indices_x = np.where(x == most_freq_x)[0]
indices_y = np.where(y == most_freq_y)[0]
print(f"Most frequent value in x: {most_freq_x}, Indices: {indices_x}")
print(f"Most frequent value in y: {most_freq_y}, Indices: {indices_y}")

Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


In [8]:
# Q3: Accessing elements in a 2D array
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("1st row, 2nd column:", arr_2d[0, 1])
print("3rd row, 1st column:", arr_2d[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [18]:
# Q4: Creating an array with 25 evenly spaced numbers from 10 to 100
Krishnarsh = np.linspace(10, 100, 25)
print("Array:", Krishnarsh)
print("Dimensions:", Krishnarsh.ndim)
print("Shape:", Krishnarsh.shape)
print("Total Elements:", Krishnarsh.size)
print("Data Type:", Krishnarsh.dtype)
print("Total Bytes:", Krishnarsh.nbytes)

# Reshape and Transpose
reshaped_array = Krishnarsh.reshape(5, 5)
print("Reshaped Array:", reshaped_array)
print("Transpose using T:", reshaped_array.T)
print("Transpose using reshape:", reshaped_array.reshape(5, 5).T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes: 200
Reshaped Array: [[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]
Transpose using T: [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]
Transpose using reshape: [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


In [28]:
# Q5: Creating a 2D array and computing statistics
ucs420_Krishnarsh = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Mean:", np.mean(ucs420_Krishnarsh))
print("Median:", np.median(ucs420_Krishnarsh))
print("Max:", np.max(ucs420_Krishnarsh))
print("Min:", np.min(ucs420_Krishnarsh))
print("Unique Elements:", np.unique(ucs420_Krishnarsh))

# Reshaping and Resizing
reshaped_ucs420_Krishnarsh = ucs420_Krishnarsh.reshape(4, 3)
print("Reshaped to 4x3:", reshaped_ucs420_Krishnarsh)
resized_ucs420_Krishnarsh = np.resize(ucs420_Krishnarsh, (2, 3))
print("Resized to 2x3:", resized_ucs420_Krishnarsh)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped to 4x3: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized to 2x3: [[10 20 30]
 [40 50 60]]
